### PR TITLE
Decrease tests flakyness

### LINKED ISSUE #343: Window related tests are failing randomly
### Describe the bug

Some tests (mostly those requiring the client to acknowledge a configure) can fail at random.

I observed to kind of failure:
- Test failing
- Test locking-up/being in an infinite loop.

### Reproduction steps

Run tests a bunch of time

### Relevant parts of config

N/A

### Version info

pinnacle 0.1.0

Build Info:
    Build profile: debug
    rustc version: 1.88.0
    Branch: main
    Commit: 4efe15f (Merge pull request #341 from Ph4ntomas/window_handle-move-to-output_fix-return)

### Distro

Arch

### GPU

Irrelevant

### Config language

Lua

### PR DESCRIPTION
**Pull request by Ph4ntomas**
This is an attempt to reduce test flakyness by waiting for some events before proceeding.

Namely:
- wait for pending transactions to be empty
- waiting for the client to receive a configure event when we expect one.

As far as I can tell, this fixes most spurious failure caused by some assertion running before the state was updated.

What isn't fixed (yet) is the event loop locking up in some tests, ~~which make some tests wait indefinitely.~~
EDIT: No more infinite loop. The `dispatch_until` function was causing these, and can now timeout. This makes the tests fail, but at least it fails with output & backtrace, and it's not half the tests that are stuck.

Fixes #343

### CODE REVIEW

**Comment by Ph4ntomas** [comment]
Hopefully we shouldn't see timeouts now.

I'm leaving the timeout behavior since it's good to know if a test is badly behaved, but hopefully if we trip it from now on, it will be for a legitimate reason.

The last few commits ([c6856a0](https://github.com/pinnacle-comp/pinnacle/pull/345/commits/c6856a03303e1943f2ab4698529276efe16c21ca) and after) are some changes to the logging I did to help me troubleshoot the tests. Since I found them useful, I've added them here. 

If heavy changes are needed on these commits, let me know, I'll move them on another PR to unblock this one.
Same if you me want to drop them (although I think we should at least keep c6856a0 and the `__tostring` part of 00c0cf5, but I can open a new PR if needed)

File: api/lua/pinnacle/grpc/stream_extension.lua
Comment (Ottatop) [inline api/lua/pinnacle/grpc/stream_extension.lua:1]: The contents of this file instead need to be copy-pasted into `api/lua/build/grpc_client.lua` so it can get generated separately for both the pinnacle and snowcap apis.

File: tests/integration/common/fixture.rs [hunk 1]
```diff
@@ -78,9 +80,14 @@ impl Fixture {
             event_loop,
             state,
             _test_guard,
+            timeout: Duration::from_secs(DEFAULT_TIMEOUT),
         }
     }
 
+    pub fn _set_timeout(&mut self, timeout: Duration) {
+        self.timeout = timeout;
+    }
```
Comment (Ottatop) [inline tests/integration/common/fixture.rs]: Is this used anywhere?

File: tests/integration/common/fixture.rs [hunk 2]
```diff
@@ -35,6 +36,7 @@ struct State {
 }
 
 static OUTPUT_COUNTER: AtomicU32 = AtomicU32::new(0);
+static DEFAULT_TIMEOUT: u64 = 60;
```
Comment (Ottatop) [inline tests/integration/common/fixture.rs]: This should be a const `Duration` instead of a static `u64`

File: tests/integration/common/fixture.rs [hunk 3]
```diff
@@ -257,19 +296,59 @@ impl Fixture {
...
     }
 
     pub fn client(&mut self, id: ClientId) -> &mut Client {
         self.state.client(id)
     }
+
+    /// Wait for all outstanding transaction and configure to be handled.
+    ///
+    /// If timeout is reached, stop with false.
+    pub fn flush(&mut self, timeout: Duration) -> bool {
```
Comment (Ottatop) [inline tests/integration/common/fixture.rs]: If all the calls to flush have an `assert` around them, I think we should just panic on timeout here instead of returning a bool.

File: tests/integration/common/fixture.rs [hunk 4]
```diff
@@ -257,19 +296,59 @@ impl Fixture {
...
+            if start.elapsed() >= timeout {
+                return false;
+            }
+        }
+
+        true
+    }
+
+    /// Wait for a client to receive a configure, dispatching in the meantime.
+    pub fn wait_client_configure(&mut self, id: ClientId, timeout: Duration) -> bool {
```
Comment (Ottatop) [inline tests/integration/common/fixture.rs]: Same here

File: tests/integration/api/window.rs [hunk 5]
```diff
@@ -145,11 +147,8 @@ fn window_handle_set_geometry_floating() {
             },
         }
 
-        fixture
-            .client(client_id)
-            .window_for_surface(&surface)
-            .ack_and_commit();
-        fixture.roundtrip(client_id);
+        assert!(fixture.wait_client_configure(client_id, Duration::from_secs(10)));
+        assert!(fixture.flush(Duration::from_secs(10)));
```
Comment (Ottatop) [inline tests/integration/api/window.rs]: We should make a const duration and use it in place of all these `from_secs` so we can change it easily if needed. Or maybe even just remove the timeout param altogether and use the fixture's `timeout` field.

File: tests/integration/api/window.rs [hunk 6]
```diff
@@ -183,11 +182,7 @@ fn window_handle_set_geometry_tiled_does_not_change_geometry() {
             },
         }
 
-        fixture
-            .client(client_id)
-            .window_for_surface(&surface)
-            .ack_and_commit();
-        fixture.roundtrip(client_id);
+        assert!(fixture.flush(Duration::from_secs(10)));
```
Comment (Ottatop) [inline tests/integration/api/window.rs]: Is there supposed to be a `wait_client_configure` before this?

**Review by Ottatop — COMMENTED** [review]
Think it's fine to keep the logging stuff in this PR.

File: tests/integration/api/window.rs (hunk 5 above)
Comment (Ph4ntomas) [reply tests/integration/api/window.rs]: Yeah agreed.

I don't think I want to use the fixture timeout here, as I'd rather keep that one larger.

10s is already way overkill on these, but indeed , a const or a second 'wait pending timeout' on the fixture would be better a good idea

File: tests/integration/common/fixture.rs (hunk 1 above)
Comment (Ph4ntomas) [reply tests/integration/common/fixture.rs]: Not anymore. 

I'll remove the method for the time being, but I'll leave in the member variable. I'd rather keep the timeout configurable if we need to increase it for some tests at some point.

File: tests/integration/api/window.rs (hunk 6 above)
Comment (Ph4ntomas) [reply tests/integration/api/window.rs]: `wait_client_configure` will block if the client never receive a configure.
Here tiled clients should not receive a configure, so the function will timeout (and panic with the requested changes).

`flush` is there to wait for transaction if one is generated and prevent the test from succeeding due to a race-condition. The function will ack configure as needed to make the transactions proceed.

File: tests/integration/api/window.rs (hunk 5 above)
Comment (Ph4ntomas) [reply tests/integration/api/window.rs]: > I don't think I want to use the fixture timeout here, as I'd rather keep that one larger.

I shouldn't have commented before grabbing a coffee. Since the test fails either way, there's no point in over-engineering this. I'll use the fixture timeout.
